### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SVallant** [XSDiVer/ioBroker.time_switch_clock#47]
Hi,
ich bin über deinen Adapter "gestolpert". Ich fnde die Idee dahinter niocht schlecht.
Frage:
"Überleben" deine Schedules einen Adapter Restart ?
Wenn zum Beispiel ein Ausgang angesteuert wird, der nach 2 Minuten wieder aus sein soll. Nach einer Minute wird dein Adapter neu gestartet. Wird dann nach einer weiteren Minute der Ausgang ausgeschaltet ??

Danke
Sepp

**Comment by XSDiVer** [comment]
Hallo Sepp,

wenn der Adapter neu gestartet wird, muss man die Schedules neu setzen, da sie beim beenden des Adapters gelöscht werden. 

Das würde auch so sein wenn man Chronjobs beim Startup eines Rechners einließt. Bei einem Neustart, werden sie wieder aktiviert. Die vor dem Neustart sind weg :o)

mfg, XSD
